In [1]:
#Different classification algorithms for building predictive models.
from sklearn.linear_model import LogisticRegression, SGDClassifier  
from sklearn.tree import DecisionTreeClassifier   
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
#Scaling and encoding
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
import pandas as pd
import numpy as np
#Plotting
import matplotlib.pyplot as plt   
import seaborn as sns
#Evaluation
from sklearn.metrics import r2_score, accuracy_score, classification_report, confusion_matrix       
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.model_selection import train_test_split, GridSearchCV, KFold, cross_val_score
from scipy.stats import zscore
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
import xgboost as xgb

In [2]:
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt   
import seaborn as sns
from sklearn.metrics import r2_score, accuracy_score, classification_report, confusion_matrix       
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.model_selection import train_test_split, GridSearchCV, KFold, cross_val_score
from scipy.stats import zscore
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

In [3]:
train = pd.read_csv(r"D:\mlopset\train_set_ml.csv")

In [4]:
train.head()

,checkin_acc,duration,credit_history,amount,savings_acc,present_emp_since,inst_rate,personal_status,residing_since,age,inst_plans,num_credits,job,status
0,A14,27,A32,5190,A65,A75,4,A93,4,48,A143,4,A173,0
1,A11,21,A32,3357,A64,A72,4,A92,2,29,A141,1,A173,0
2,A14,12,A32,1963,A61,A74,4,A93,2,31,A143,2,A174,0
3,A11,12,A32,3386,A61,A75,3,A93,4,35,A143,1,A173,1
4,A12,12,A34,1995,A62,A72,4,A93,1,27,A143,1,A173,0

In [5]:
test = pd.read_csv(r"D:\mlopset\test_set_ml.csv")

In [6]:
test.head()

,checkin_acc,duration,credit_history,amount,savings_acc,present_emp_since,inst_rate,personal_status,residing_since,age,inst_plans,num_credits,job,status
0,A12,8,A32,907,A61,A72,3,A94,2,26,A143,1,A173,0
1,A14,18,A32,1505,A61,A73,4,A93,2,32,A143,1,A174,0
2,A14,12,A34,1264,A65,A75,4,A93,4,57,A143,1,A172,0
3,A14,15,A32,3186,A64,A74,2,A92,3,20,A143,1,A173,0
4,A12,12,A34,1424,A61,A74,4,A93,3,26,A143,1,A173,0

In [7]:
X_train = train.drop('status', axis =1)
y_train = train.status

In [8]:
X_train

,checkin_acc,duration,credit_history,amount,savings_acc,present_emp_since,inst_rate,personal_status,residing_since,age,inst_plans,num_credits,job
0,A14,27,A32,5190,A65,A75,4,A93,4,48,A143,4,A173
1,A11,21,A32,3357,A64,A72,4,A92,2,29,A141,1,A173
2,A14,12,A32,1963,A61,A74,4,A93,2,31,A143,2,A174
3,A11,12,A32,3386,A61,A75,3,A93,4,35,A143,1,A173
4,A12,12,A34,1995,A62,A72,4,A93,1,27,A143,1,A173
...,...,...,...,...,...,...,...,...,...,...,...,...,...
830,A11,42,A32,7174,A65,A74,4,A92,3,30,A143,1,A174
831,A11,24,A34,6419,A61,A75,2,A92,4,44,A143,2,A174
832,A14,30,A32,1867,A65,A75,4,A93,4,58,A143,1,A173
833,A14,24,A33,4679,A61,A74,3,A93,3,35,A143,2,A172
834,A12,18,A32,6260,A61,A74,3,A93,3,28,A143,1,A172

In [9]:
y_train

0      0
1      0
2      0
3      1
4      0
      ..
830    1
831    0
832    0
833    0
834    0
Name: status, Length: 835, dtype: int64

In [10]:
X_test = test.drop('status', axis =1)
y_test = test.status

In [11]:
X_test

,checkin_acc,duration,credit_history,amount,savings_acc,present_emp_since,inst_rate,personal_status,residing_since,age,inst_plans,num_credits,job
0,A12,8,A32,907,A61,A72,3,A94,2,26,A143,1,A173
1,A14,18,A32,1505,A61,A73,4,A93,2,32,A143,1,A174
2,A14,12,A34,1264,A65,A75,4,A93,4,57,A143,1,A172
3,A14,15,A32,3186,A64,A74,2,A92,3,20,A143,1,A173
4,A12,12,A34,1424,A61,A74,4,A93,3,26,A143,1,A173
...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,A13,36,A32,5848,A61,A73,4,A93,1,24,A143,1,A173
89,A11,24,A34,1231,A64,A75,4,A92,4,57,A143,2,A174
90,A12,60,A32,6288,A61,A73,4,A93,4,42,A143,1,A173
91,A11,12,A32,708,A61,A73,2,A93,3,38,A143,1,A172
92,A14,24,A34,1287,A64,A75,4,A92,4,37,A143,2,A173

In [12]:
y_test

0     0
1     0
2     0
3     0
4     0
     ..
88    0
89    0
90    1
91    0
92    0
Name: status, Length: 93, dtype: int64

In [13]:
import pickle
with open('model.pkl', 'rb') as x:
    model = pickle.load(x)

In [14]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['duration', 'amount', 'inst_rate', 'residing_since', 'age',
       'num_credits'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEnc...
                               feature_types=None, gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, random_state=None, ...))])

In [15]:
y_hat= model.predict(X_train)

In [16]:
y_hat_test = model.predict(X_test)

In [17]:
accuracy_score(y_test,y_hat_test)

0.7849462365591398